#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"

  rbenv install --skip-existing

  which bundle 2>&1 >/dev/null || {
  gem install bundler
  rbenv rehash
}
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle install
fi
